apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
images:
- name: docker.io/bcubkcu/test-app
  newName: docker.io/bcubkcu/test-app
  newTag: 1.0.2
